site_name: Platitudes
site_url: https://platitudes.maxwellrules.com
repo_url: https://github.com/GCBallesteros/platitudes
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            ignore_init_summary: false
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
nav:
  - 'Home': index.md
  - 'Extended Example': extended_example.md
  - Supported Types:
    - str: types/str.md
    - numbers: types/numbers.md
    - datetime: types/datetime.md
    - UUID: types/uuid.md 
    - Path: types/path.md
    - Enum/Choices: types/enum.md
  - API:
    - Platitudes: api/platitudes.md
    - Argument: api/argument.md
    - Exit: api/exit.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
